- pipeline.id: initial_index-pipeline
  path.config: "/usr/share/logstash/pipeline/initial_index.conf"
- pipeline.id: keep_sync-pipeline
  path.config: "/usr/share/logstash/pipeline/keep_sync.conf"
- pipeline.id: keep_sync_deletions-pipeline
  path.config: "/usr/share/logstash/pipeline/keep_sync_deletions.conf"